class InputState:
    """Input state for keyboard and mouse."""

    mouse_pos: tuple[int, int]
    mouse_rel: tuple[int, int]
    mouse_captured: bool

    def __init__(self) -> None: ...
    def prepare_update(self) -> None: ...
    def is_key_down(self, key: str) -> bool: ...
    def is_mouse_down(self, btn: str) -> bool: ...